Home/urls.py
from . import views
from django.urls import path


app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path("solutions/", views.our_solutions, name="our_solutions"),
    path("faq", views.FAQ, name="FAQ"),
    path("details/<int:id>/<slug:slug>", views.project_details, name="project_details"),
    path("solutions/professional", views.professional_projects, name="professional_projects"),
    path("solutions/educational", views.educational_projects, name="educational_projects"),
    path("aboutMe/", views.about_me, name="about_me"),
    path("contactMe/", views.contact_me, name="contact_me"),
    path("services/", views.our_services, name="our_services"),
    path("myTranslator/", views.translator_hype, name="translator_hype"),

]

brillanteLabs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls", namespace="Home")),
    path("client/", include("client.urls", namespace="client")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Project(models.Model):
    project_type_choices = [
        ('Professional', 'Professional'),
        ('Educational', 'Educational')
    ]

    project_slug = models.SlugField(max_length=200, blank=True)

    project_name = models.CharField(max_length=75, blank=False)
    thumbnail = models.ImageField(upload_to='projects/', blank=True)
    video_link = models.URLField(blank=False)
    project_link = models.URLField(blank=False)
    story = models.TextField()
    functionalities = models.TextField()
    testimonial = models.TextField()
    # accent color for card design, enter in form of hex.
    accent_color = models.CharField(max_length=50, blank=False)
    tag_1 = models.CharField(max_length=25, blank=True)
    tag_2 = models.CharField(max_length=25, blank=True)
    tag_3 = models.CharField(max_length=25, blank=True)
    project_type = models.CharField(choices=project_type_choices, blank=False, max_length=50)

    def __str__(self):
        return self.project_name

    def get_absolute_url(self):
        return reverse("Home:project_details",
            args=[self.id, self.project_slug])


class ProjectGallery(models.Model):
    image = models.ImageField(upload_to='gallery/')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    caption = models.CharField(max_length=35)

    def __str__(self):
        return str(self.image)

Home/views.py
from django.shortcuts import render
from .models import Project, ProjectGallery
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template


# Create your views here.
def home(request):
    return render(request, "index.html")

def translator_hype(request):
    return render(request, "translator_hype.html")

def our_services(request):
    return render(request, "our_services.html")

def our_solutions(request):
    # return all the projects from our database and pass them into template.
    projects = Project.objects.all()

    return render(request, "solutions.html", {'projects': projects})

def professional_projects(request):
    projects = Project.objects.filter(project_type='Professional')

    return render(request, "solutions.html", {'projects': projects})

def educational_projects(request):
    projects = Project.objects.filter(project_type='Educational')
    return render(request, "solutions.html", {'projects': projects})

def FAQ(request):
    return render(request, "FAQ.html")

def about_me(request):
    return render(request, "about_me.html")

def contact_me(request):
    if request.method == "POST":
        # get the content that was submitted.
        name = request.POST['name']
        occupation = request.POST['occupation']
        phone = request.POST['tel']
        email = request.POST['email']

        content = request.POST['content']

        # need to group the data and send it in an e-mail format. we will
        # make use of client side logic to ensure that all the data is
        # valid, perhaps just for the e-mail.
        send_mail(
            "Thank You For Choosing Brillante Labs",
            "Hello, We Appreciate you for reaching out to us. A "
            "representative will soon reach out to you.",
            "Don't Reply <do_not_reply@domain.example>",
            [email],
            fail_silently=False,
        )
        plaintext = get_template("email/admin_confirmation.txt")
        content = ({
            'user': name,
            'email': email,
            'phone': phone,
            'occupation': occupation,
            'details': content
        })

        text_content = plaintext.render(content)

        msg = EmailMultiAlternatives("A New Quote Has Been Created",
                                     text_content,
                                     "Don't Reply <do_not_reply@domain.example>",
                                     ['cfanito797@icloud.com'])
        msg.send()

        return redirect('Home:home')

    return render(request, "let's_talk!.html")

def project_details(request, id, slug):
    # query the correct project.

    project = get_object_or_404 (Project,
        id=id,
        project_slug=slug,
    )

    # get all the images pertaining to this project.
    gallery = ProjectGallery.objects.filter(project_id=id).all()


    return render(request, "project_details.html", {'project': project, 'gallery': gallery})

Home/templates/FAQ.html
{% extends 'index.html' %}

{% load static %}


{% block mainbody %}
<div id="top_padding" style="margin-top: 10vh;">
    </div>


<div class="columns is-centered is-mobile mt-5 pt-5 mb-5 pb-5"
     id="content">

    <div
            class="column is-half-fullhd is-three-quarters-tablet is-full-mobile is-justify-content-center">

        <div id="imageContainer" class="has-text-centered ">
            <img src="{% static 'AdobeStock_537400208.png' %}" width="500">
        </div>

        <div id="whatDoesAWebsiteCost"
             class="p-5 ml-5 pl-5">
            <h1 class="title has-text-white has-text-weight-bold mt-5" style="font-family:
                Charter;">
                How Much Does A Website Cost?</h1>
            <p class="text has-text-white has-text-weight-bold">There are many factors
                that are considered when calculating the cost of a website such as:</p>
            <ul style="display: list-item;" class="ml-5 pl-5 has-text-weight-bold">
                <li>How many pages you plan to implement to your website.</li>
                <li>The features and services you would like to implement on your
                    website.
                </li>
                <li>The branding work that would need to be done on your website.</li>
                <li>The amount of traffic you expect to generate on your website.</li>
            </ul>


            <p class="text has-text-white has-text-weight-bold pt-5 mt-5">Some of the
                post-launch
                (per-monthly)
                expenses you can expect would include: </p>
            <ul style="display: list-item;" class="ml-5 pl-5 has-text-weight-bold">
                <li>Per-month hosting operation cost via AWS.</li>
                <li>SEO Research & Branding</li>
            </ul>

        </div>

        <div id="ourProcess" class="p-5 ml-5 pl-5">
            <h1 class="title has-text-white">What Does Our Process Entail?</h1>
        </div>

        <div class="step" class="p-5 ml-5 pl-5">
            <div class="columns">

                <div class="column is-one-quarter has-text-centered mt-4 ml-3">
                    <img src="{% static 'icons8-consultation-50.png' %}">
                </div>

                <div class="column p-5 ml-5 pl-5">
                    <p class="text has-text-white is-size-5 has-text-weight-bold">1.
                        Initial Consultation</p>
                    <p class="text has-text-white pl-2">Through our initial consultation,
                        we
                        take our time to get to know your and your business. We analyze
                        your needs and present you a project scope and initial price.
                    </p>
                </div>
            </div>
        </div>

        <div class="step" class="p-5 ml-5 pl-5 mt-5">
            <div class="columns">

                <div class="column is-one-quarter has-text-centered mt-4 ml-3">
                    <img src="{% static 'prototype.png' %}" width="65" height="65">
                </div>

                <div class="column p-5 ml-5 pl-5">
                    <p class="text has-text-white is-size-5 has-text-weight-bold">2.
                        Design Prototypes</p>
                    <p class="text has-text-white pl-2">During this phase of the project we
                        present you with our design prototypes, you tell us what you like,
                        what you don't like and what changes you want made to the design of
                        your website.
                    </p>
                </div>
            </div>
        </div>

        <div class="step" class="p-5 ml-5 pl-5">
            <div class="columns">

                <div class="column is-one-quarter has-text-centered mt-4 ml-3">
                    <img src="{% static 'icons8-laptop-coding-96.png' %}" width="75"
                         height="75">
                </div>

                <div class="column p-5 ml-5 pl-5 mt-3">
                    <p class="text has-text-white is-size-5 has-text-weight-bold">3.
                        Design & Development</p>
                    <p class="text has-text-white pl-2">
                        This is the phase of the project where the rubber really meets
                        the road. Where we put our head down and work until your solutions
                        have been met to your satisfaction, revisions are required on your end.
                    </p>
                </div>
            </div>
        </div>

        <div class="step" class="p-5 ml-5 pl-5">
            <div class="columns">

                <div class="column is-one-quarter has-text-centered mt-4 ml-3">
                    <img src="{% static 'icon-cloud.png' %}" width="75"
                         height="75">
                </div>

                <div class="column p-5 ml-5 pl-5 mt-3">
                    <p class="text has-text-white is-size-5 has-text-weight-bold">4.
                        Cloud Hosting</p>
                    <p class="text has-text-white pl-2">
                        This is where your project is fully brought to life and only until
                        all revisions have been made is your project hosted on our cloud
                        hosting provider.
                    </p>
                </div>
            </div>
        </div>

        <div class="step" class="p-5 ml-5 pl-5">
            <div class="columns">

                <div class="column is-one-quarter has-text-centered mt-4 ml-3">
                    <img src="{% static 'partnership.png' %}" width="75"
                         height="75">
                </div>

                <div class="column p-5 ml-5 pl-5 mt-3">
                    <p class="text has-text-white is-size-5 has-text-weight-bold">5.
                        Continued Partnership</p>
                    <p class="text has-text-white pl-2">
                        Just because your website is live does not mean that this is the end
                        of the road, we continue our partnership with every single one of
                        our clients.
                    </p>
                </div>
            </div>
        </div>

        <div id="button_container" class="has-text-centered pt-3 mt-5">
            <a class="button is-medium has-text-white p-5
                has-text-weight-bold"
               href="{% url 'Home:contact_me' %}" style="background-color:
                #BAA651; border: none; font-family: Charter;">
                Let's Talk!
            </a>
        </div>

    </div>
</div>


</div>


{% endblock %}

{% block javascript %}
    <script src="{% static 'js/navbar_change.js' %}"></script>
{% endblock %}

Home/templates/about_me.html
{% extends 'index.html' %}
{% load static %}


{% block mainbody %}

<div id="top_padding" style="margin-top: 15vh;">
</div>


<section class="hero " id="content" style="min-height: 65vh;">

    <div class="columns is-flex-fullhd  is-align-content-center is-align-items-center">
        <div class="is-hidden-mobile" style="margin-left: 5%;"></div>

        <div class="column m-5 p-5">

            <div class="hr" style="width: 35%; border: 2px solid
                                red;"></div>
            <h1 class="is-size-3-fullhd is-size-4-tablet is-size-4-mobile title has-text-white
            has-text-weight-bold mt-5 pt-5">Meet Juan<br/>Your <span style="color: red;">KO
            </span> Web
                Developer & Designer.</h1>


            <p class="text has-text-white mb-5 pb-5" style="font-weight: bold;">Designing &
                Developing KO Web
                Experiences
                is the mission of KO'de By Juan. Each project that we do is a unique creative
                endeavor. In my free time, I find it crucially important to recharge my
                creative batteries. Whether that be with watching films or pursuing other
                creative hobbies.
            </p>

            <div class="hr" style="width: 100%; border: 1px solid
                                blue; opacity: 0.55;"></div>


        </div>


        <div class="column has-text-centered">

            <img src="{% static 'about_me-3.png' %}" style="border-radius: 50%;" width="550"
                 height="550">

        </div>

    </div>



</section>


<section class="hero" id="my_story">

    <div class="columns p-0 is-align-content-center is-align-items-center">

        <div class="columns is-flex-fullhd m-5 p-5">

            <div id="image_container" class="has-text-centered-mobile">
                <img src="{% static 'my_story_1.jpeg' %}" width="550" height="550"
                     style="border-radius: 5%;">
            </div>

            <div class="is-hidden-mobile" style="margin-left: 5%;"></div>


            <div id="my_story_container" class="column is-two-fifths-fullhd
                is-half-tablet is-full-mobile">

                <div class="is-hidden-mobile" style="margin-top: 15%;"></div>

                <h1 class="title is-size-4 has-text-white
                    has-text-weight-bold has-text-left"><span style="color: #9F8B3B;
                    font-weight:
                    bold;"><</span> My
                    Story <span style="color: #9F8B3B; font-weight: bold;">\></span></h1>

                <h1 class="title is-size-4 has-text-white has-text-weight-bold">How I
                    Started My Web Development Journey.</h1>
                <p class="text has-text-white has-text-weight-bold">I began my web
                    development journey during my undergraduate tenure, where I elected
                    to take a course outside my plan of study. There I began
                    developing sophisticated websites and learned the power of the
                    technologies that run the web.
                </p>
            </div>
        </div>

    </div>


    <div class="columns p-0 is-align-content-center is-align-items-center">
        <div class="is-hidden-mobile" style="margin-left: 5%;"></div>


        <div class="columns is-flex-fullhd m-5 p-5">

            <div id="my_story_container" class="column is-two-fifths-fullhd
                is-half-tablet is-full-mobile">

                <div class="is-hidden-mobile" style="margin-top: 15%;"></div>

                <h1 class="title is-size-4 has-text-white
                    has-text-weight-bold"><span style="color: #9F8B3B; font-weight:
                    bold;"><</span> My
                    Story <span style="color: #9F8B3B; font-weight: bold;">\></span></h1>

                <h1 class="title is-size-4 has-text-white has-text-weight-bold">My
                    very first web development project.</h1>
                <p class="text has-text-white has-text-weight-bold">Like all
                    programmers alike my first web development project was a simple web
                    page that displayed "Hello World!". But my first real world project
                    in which the project was taken outside the usual classroom
                    context, was a nail salon scheduling web application.
                </p>

                <!--
                <div id="button-container" class="has-text-centered mt-2">
                    <a class="button is-medium mt-3 has-text-weight-bold has-text-weight-white"
                            id="messageButton"
                            style="background-color:
                #BAA651; border: none; color: white;">View
                        Project</a>
                </div>

                -->

            </div>

            <div class="is-hidden-mobile" style="margin-left: 5%;"></div>

            <div class="" style="margin-top: 15%;"></div>


            <div id="image_container" class="has-text-centered-mobile">
                <img src="{% static 'my_story_2.jpeg' %}" width="550" height="550"
                     style="border-radius: 5%;">
            </div>
        </div>

    </div>

    <div class="column has-text-center">
        <div class="hr" style="width: 75%; margin-left: 12%; border: 3px solid
                                #9F8B3B; opacity: 0.55;"></div>
    </div>


</section>


<section class="hero" id="my_experience">

    <div id="text-block">

        <h1 class="title is-size-4 has-text-white
                    has-text-weight-bold p-3 m-3"><span style="color:
                    #9F8B3B;
                    font-weight:
                    bold;"><</span> My
            Experience <span style="color: #9F8B3B; font-weight: bold;">\></span></h1>
    </div>

    <div class="columns is-centered">
        <div
                class="column is-half-fullhd is-three-quarters-tablet is-full-mobile has-text-centered">

            <p class="subtitle has-text-white pl-3 m-5">"I have over 5 years of
                professional IT
                experience and I have completed 3+ professional freelance projects as
                well as various educational projects."</p>

            <div id="button_container" class="has-text-centered">
                <a class="button is-medium has-text-white p-5
                has-text-weight-bold"
                   href="{% url 'Home:contact_me' %}" style="background-color:
                #BAA651; border: none; font-family: Charter;">
                    Let's Talk!
                </a>
            </div>

        </div>

    </div>

    <div class="columns pl-3 is-centered">


        <div class="column is-half-fullhd is-flex-tablet is-full-mobile
            has-text-centered-mobile
            is-justify-content-center">


            <div id="skill_set" class="mt-5">
                <h1 class="title is-size-4" style="color: #BAA561;">Skill Set</h1>
                <div class="columns is-fullhd">
                    <div class="column is-fullhd has-text-weight-bold
                        is-justify-content-left">
                        <p class="text is-size-5 has-text-white">HTML5</p>
                        <p class="text has-text-white is-size-5">CSS3</p>
                        <p class="text has-text-white is-size-5">JavaScript</p>
                        <p class="text has-text-white is-size-5">SQL</p>
                    </div>
                    <div class="column is-fullhd has-text-weight-bold">
                        <p class="text is-size-5 has-text-white">Python</p>
                        <p class="text has-text-white is-size-5">Django</p>
                        <p class="text has-text-white is-size-5">Unix/Ubuntu</p>
                        <p class="text has-text-white is-size-5">AWS</p>

                    </div>
                </div>

            </div>

            <div class="column is-one-fifth-tablet is-one-fifth-fullhd
                is-hidden-mobile"></div>


            <div id="skill_set" class="mt-5">
                <h1 class="title is-size-4" style="color: #BAA561;">Top Clients</h1>
                <div class="columns is-fullhd">
                    <div class="column is-fullhd has-text-weight-bold">
                        <p class="text is-size-5 has-text-white">Remodeling Dreams
                            Construction</p>
                        <p class="text has-text-white is-size-5">Golden Auto Repair</p>
                    </div>

                </div>

            </div>


        </div>

    </div>


    <div id="education&credentials">
        <h1 class="title is-size-4 has-text-white
                    has-text-weight-bold p-3 m-3"><span style="color:
                    #9F8B3B;
                    font-weight:
                    bold;"><</span> My
            Experience <span style="color: #9F8B3B; font-weight: bold;">\></span></h1>

        <h1 class="title has-text-white has-text-weight-bold is-size-4 p-5 m-5">Past
            Education &
            Credentials</h1>

        <div class="columns is-flex-tablet is-align-items-center p-5 m-5"
             style="margin-left: 5%">
            <div class="column is-half">

                <p class="text has-text-white is-size-4 is-size-5-mobile">Omaha
                    University
                    <span
                            style="color: #BAA561; font-weight: bold;"> / </span>
                    Aug.
                    2018 -
                    Dec. 2022</p>
                <p class="text has-text-white is-size-4 is-size-5-mobile">B.S. Computer
                    Science</p>

                <p class="text has-text-white"></p>
            </div>

            <div class="column is-half has-text-centered">
                <img src="{% static 'uno_alum.png' %}" width="150" height="150">
            </div>
        </div>


        <div class="columns is-flex-tablet is-align-items-center p-5 m-5"
             style="margin-left: 5%">
            <div class="column is-half">

                <p class="text has-text-white is-size-4 is-size-5-mobile">Union Pacific
                    Railroad
                    <span
                            style="color: #BAA561; font-weight: bold;"> / </span> Dec.
                    2019</p>
                <p class="text has-text-white is-size-4 is-size-5-mobile">IT
                    Infrastructure Intern</p>

                <p class="text has-text-white"></p>
            </div>

            <div class="column is-half has-text-centered">
                <img src="{% static 'union_pacific_logo.png' %}" width="150" height="150">
            </div>
        </div>

    </div>

    <div class="column has-text-center">
        <div class="hr" style="width: 75%; margin-left: 12%; border: 3px solid
                                #9F8B3B; opacity: 0.55;"></div>
    </div>

</section>

{% endblock %}

{% block javascript %}

<script src="{% static 'js/navbar_change.js' %}"></script>

{% endblock %}

Home/templates/our_services.html
{% extends 'index.html' %}
{% load static %}


{% block mainbody %}





{% endblock %}

Home/templates/solutions.html
{% extends 'index.html' %}
{% load static %}


{% block mainbody %}
<div id="top_padding" style="margin-top: 10vh;">
</div>


<section class="hero pt-5" id="content">

    <div id="heading">
        <h1 class="title has-text-centered has-text-white">View Our Work Below</h1>
    </div>

    <div id="tabs" style="text-align: center; padding: 0;" class="mt-5">
        <!-- one tab for displaying professional work, and another for displaying
        undergraduate work.-->

        <!-- of course, we will want to give a description for each of them.-->

        <ul style="display: flex; align-items: center;
            justify-content: center;" class="has-text-white mt-5">

            <div id="professional_projects" class="tab" style="background-color:
                #BAA651; border-radius: 5px;"
                 class="m-1">
                <li style="list-style-type: none;">
                    <a style="text-align: center; opacity: 0.33;"
                       href="{% url 'Home:professional_projects' %}">
                        <p class="text has-text-white p-2 ml-2 mr-2
                        has-text-weight-semibold">Professional</p>
                    </a>
                </li>
            </div>

            &nbsp;


            <div class="tab"
                 style="background-color:
                #BAA651; border-radius: 5px;"
                 class="m-1">
                <li style="list-style-type: none;">
                    <a href="{% url 'Home:educational_projects' %}">
                        <p class="text has-text-white p-2 ml-2 mr-2
                        has-text-centered has-text-weight-semibold">Educational</p>
                    </a>
                </li>
            </div>
        </ul>
    </div>
</section>


<section class="hero" id="our_work">
    <div class="p-3 columns is-centered-mobile is-centered-tablet is-centered-fullhd
        is-mobile
        is-flex-wrap-wrap is-justify-content-left-fullhd is-justify-content-center mt-5">

        <!-- for each project create a responsive card -->
        <!-- two-fifths for fullhd, four-fifths-tablet, and full for mobile -->
        {% for project in projects %}
        <div class="column is-one-quarter-fullhd is-two-fifths-widescreen
                is-two-fifths-desktop is-half-tablet is-full-mobile"
             id="project_card">

            <a href="{{ project.get_absolute_url }}" id="project">
                <div class="card m-3" id="project" style="background-color:
                    #292929;
                    border-radius:
                    1%;">
                    <div class="card-image">
                        <figure class="image is-4by3">
                            <div class="blur-load">

                                <img src="/media/{{ project.thumbnail }}"
                                        alt="Placeholder image" loading="lazy"/>
                            </div>
                        </figure>
                    </div>
                    <div class="card-content p-5">

                        <div class="media-content">
                            <p class="title is-5 has-text-white
                                    has-text-weight-semibold has-text-centered"
                               style="font-family: 'Charter';">
                                {{ project.project_name }}
                            </p>

                            <div id="hr" style="content: ''; position: absolute;
                                            background-color: {{ project.accent_color }};
                                            margin-top: 5px;
                                            height:
                                            2px; width: 50%; left: 25%;">
                            </div>


                        </div>


                    </div>

                    <div class="content p-5 has-text-centered">

                        <div class="tags are-medium is-centered">
                                <span class="tag is-dark has-text-weight-semibold p-3"
                                >{{ project.tag_1 }}</span>
                            <span class="tag is-dark has-text-weight-semibold p-3"
                            >{{ project.tag_2 }}</span>
                            <span class="tag is-dark has-text-weight-semibold p-3"
                            >{{ project.tag_3 }}</span>
                        </div>


                    </div>
                </div>
            </a>

        </div>


        {% endfor %}

    </div>

</section>


{% endblock %}

{% block javascript %}
<script src="{% static 'js/navbar_change.js' %}"></script>
{% endblock %}